### ISSUE TITLE
RMXP.exe help output breaks (question)

### ISSUE THREAD

**Issue by Ruchian** [atom0s/Steamless#108]
Steam is currently giving away a product called RPG Maker XP. 
https://store.steampowered.com/app/235900/RPG_Maker_XP/
It's main executable is RMXP.exe

Steamless seems to succesfully unpack RMXP, removing SteamStub2.1 with its default settings, but there is an unintended side effect I noticed.

RMXP is software that can be used to create something like a game and comes with internal help, as well as a help documentation file. The internal help feature is what breaks.

To see this in effect, you need to do the following:

- Create a new project.
- Open up the database. (click on tools/database or click on the icon in the top bar)
- Click on the ? button in the top. (next to the close button)
- Now click on any item in the database window.

Result:
When using the unpacked exe, all of the help content seems to have been blanked, so, instead of something useful you get Window's default help output.

Expected:
Normally the help feature provides content with information about what you're dealing with. (confirm it by using the normal exe (Steam needs to be open for this to run.)

**Comment by atom0s** [comment]
This happens with a handful of games if you are just running the unpacked exe without renaming it. Various games will use the name of the parent executable to determine the name of additional resources that are required in order to run the application/game or use extended features, such as this help feature.

To fix it, you just need to rename the unpacked executable to the real name the game expects.

  - Rename the real `RPGXP.exe` to something like `RPGXP.exe_real` to keep a backup.
  - Rename the Stemaless unpacked exe to: `RPGXP.exe` and place it in the game folder where the real one is also located.

Afterward, it should work fine and as expected.

**Comment by Ruchian** [comment]
Ah, I see. Yes, it appears you're right.
I learned something new it seems. Thanks for the answer.
