### ISSUE TITLE
Can't open Steamless in Windows XP 32-bit

### ISSUE THREAD

**Issue by footnmouth5** [atom0s/Steamless#120]
When I try to run the Steamless.exe I get an error saying that it is not a valid Win 32 application

**Comment by atom0s** [comment]
Steamless does not support Windows XP. The minimum required operating system at this time is Windows 7. This is due to Steamless being compiled against the .NET Framework v4.5.2 as its minimum required version, which itself requires Windows 7 to work.

_There are potential workarounds to make newer versions of the .NET Framework work on Windows XP, but I will not assist with that. I also do not give support for older operating systems and will not modify Steamless in any manner to make it work for anything outdated, such as Windows XP._

**Comment by Drakonas** [comment]
Almost all software on the internet has rescinded support for XP at this point. As a friend, update your operating system. You should not even be connected to the internet with XP, unless you want all your passwords and information stolen. There is no security for XP at all. You are begging for all your devices in your home to be intruded upon having that operating system online.

XP was discontinued in 2014, 10 years ago. Windows 7 was discontinued in 2020. Both are no longer recommended as mainstream operating systems.

**Comment by thekovic** [comment]
Nobody is asking for this because they're still daily driving Windows XP in 2024.

I have a retro PC with Windows 98 and Windows XP that I use to play old games in their native environment, on period appropriate hardware, for the purposes of nostalgia and because some games simply don't work properly on modern Windows (despite best efforts). I try to source my games from original discs or from GOG but some old games are on Steam. Some are DRM-free when you run from executable but some, sadly, have had Steam DRM tacked on. I can't run Steam on the retro PC, it's not even connected to the internet. Hence, why a project like this is so useful for an old PC running an old operating system.

**Comment by Drakonas** [comment]
> Nobody is asking for this because they're still daily driving Windows XP in 2024.
> 
> I have a retro PC with Windows 98 and Windows XP that I use to play old games in their native environment, on period appropriate hardware, for the purposes of nostalgia and because some games simply don't work properly on modern Windows (despite best efforts). I try to source my games from original discs or from GOG but some old games are on Steam. Some are DRM-free when you run from executable but some, sadly, have had Steam DRM tacked on. I can't run Steam on the retro PC, it's not even connected to the internet. Hence, why a project like this is so useful for an old PC running an old operating system.

Steam dropped official support for XP and Vista in 2019. Honestly if you're doing it for that purpose why not obtain the games some other way. Disc copies surely would be more stable with the operating systems they're intended for.
