### ISSUE TITLE
Cant unpack RPGVX.EXE 

### ISSUE THREAD

**Issue by LiEnby** [atom0s/Steamless#16]
Whenever i try unpack the steam verison of RPG Maker VX i get the following error:

![image](https://user-images.githubusercontent.com/39113159/55052203-e6eee380-50bc-11e9-9ef4-0438a0496607.png)

You can get the EXE here 
[RPGVX.zip](https://github.com/atom0s/Steamless/files/3011621/RPGVX.zip)

**Comment by atom0s** [comment]
Hello, the unpacker for v2 uses hard coded offsets which land up causing some files to fail like this due to the compiling shifting the data around that is needed. This is one of the unlucky files that happens to hit this problem. I am working on a fix now though and should have an update pushed in a bit which will allow a new option to use a different method to pull the offsets needed via disassembling. 

I'll respond to this ticket once its pushed.

**Comment by atom0s** [comment]
This should now be fixed and able to be unpacked using the new features of v3.0.0.8:
https://github.com/atom0s/Steamless/releases/latest
