### ISSUE TITLE
[Question/Request] cmake support ?

### ISSUE THREAD

**Issue by ShadMessa** [atom0s/Steamless#21]
Hi can you add a cmake file for compilation please ??

**Comment by atom0s** [comment]
I have no intentions on adding things like this because I don't personally use it. I'm a Windows user/developer and directly use Visual Studio. So I don't have a need or desire to do things like this, sorry.

If someone else is interested in doing it, they can make a pull request with it. But the main project will always be focused on compiling with Visual Studio itself.
