### ISSUE TITLE
64 bit support

### ISSUE THREAD

**Issue by kornos** [atom0s/Steamless#3]
Hello atom0s

Thanks very much for coding Steamless , hell of a program.

Do you intend to support 64 bit binaries?

You need 64 bit games?
I can help with that , if needed.

Regards.

**Comment by atom0s** [comment]
It's planned just haven't had the time to work on it currently.

**Comment by atom0s** [comment]
If you wish to submit .exe's that are packed with SteamStub to help with the research of this project, feel free to take a look at the topic here:
http://atom0s.com/forums/viewforum.php?f=25

I have pushed some basic starting stuff for the 64bit support of SteamStub, and I am reviewing some of the games I personally own that have it tonight. I'll see if I can get something working for at least one of the packer versions. (More or less v3.0 or v.31 if anything, v2 is going to be a bit more work due to the disassembling.)

**Comment by atom0s** [comment]
64bit support is now added as of v3.0.0.4.
