### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by sandsmark** [atom0s/Steamless#31]
I assume Linux isn't a priority, but would you be open to fixes to improve compatibility?

I tried to get this running with mono and wine, but unfortunately WPF apparently is pretty much a no-go even when installing Microsoft's dotnet runtime in wine. I'm not very familiar with c# or dotnet, but is there a simple less windows-specific way of creating UIs in C#?

And a related (possibly dumb) question; do you still have the code for the C++ version somewhere? I don't know C# at all, so I'd be more comfortable trying to get the C++ version running cross platform (and backporting whatever stuff is needed).

**Comment by w3bb** [comment]
@sandsmark https://github.com/sokie/Steamless is this it? Also +1, I would be happy with even a CLI for it.

**Comment by atom0s** [comment]
Linux is not a priority at all given that this targets Windows PE files specifically. I do not use/touch Linux at all either so I have no personal interest in working with it.

I chose to move from C++ to C# because most of the reversing scene now is making use of .NET languages over other things, so the goal was to create a more accessible project for everyone. Ideally, more work would have been done as a community to add more support for the various versions of SteamStub and so on. 

Going forward I'm debating on going back to C++ since it's my preferred language, dropping the UI altogether and making it full command-line based.  Currently, I'm busy with other projects so this is not a high priority to me since this version is working fine as-is. But restructuring things to be command-line friendly and potentially moving back to C++ is on the table when I have time to work on this again. 

The old C++ src base can be found here:
https://gitlab.com/atom0s/Steamless/-/tree/master

_Keep in mind, it's far behind the current code here though and lacks support for 64bit._

**Comment by iOrange** [comment]
Hi!

Do you have any plans on adding support for ELF executables? Not asking the Linux version of your awesome application, but and ability to unpack Linux executables.

Thanks!

**Comment by atom0s** [comment]
I do not currently have any plans to support Linux in any manner.

**Comment by liberodark** [comment]
@iOrange for linux have this : https://github.com/liberodark/steamstub
https://gitlab.com/sektour/steamstub_scripts

**Comment by iOrange** [comment]
> @iOrange for linux have this : https://github.com/liberodark/steamstub
> https://gitlab.com/sektour/steamstub_scripts

Oh, thanks!

**Comment by OdinVex** [comment]
> @iOrange for linux have this : https://github.com/liberodark/steamstub
> https://gitlab.com/sektour/steamstub_scripts

Very nice find.

**Comment by atom0s** [comment]
Closing this as I do not plan to support Linux directly. 

_When I do get time to rewrite Steamless, it will be done via .NET Core instead, which should work on any platform that can run Core. Linux should work fine then, but it still wont be directly supported as I do not use Linux at all._
