### ISSUE TITLE
grim dawn unpacks but fails to launch

### ISSUE THREAD

**Issue by marcusx2** [atom0s/Steamless#36]
The unpacked grim dawn says it needs steam.

**Comment by atom0s** [comment]
Grim Dawn uses Steamworks (steam_api.dll) as well, which this project does not remove. You either need to manually remove it, or use an emulator.

Side note; Grim Dawn also has custom protections in it, when unpacking it with Steamless, keep the .bind section in the file. Otherwise, quests and other things will break if its missing.

**Comment by marcusx2** [comment]
@atom0s  Why does it not remove Steamworks? I don't know what that is or care about it, never used Steamworks in my life. How do I safely remove it manually then? Also, Skyrim uses steamworks as well but I didn't have a problem unpacking it in the past.

**Comment by atom0s** [comment]
Because that is outside the scope of this project and directly promotes piracy which I do not condone. _Super late reply._
