### ISSUE TITLE
hey everyone! Can u tell me how it works exactly?

### ISSUE THREAD

**Issue by cherishyourlife** [atom0s/Steamless#52]
Hey,

Maybe its a stupid question, but I would be very greatful if you tell me how it works exactly?
What I should to do after open the steamless.exe file? 

~Thanks for any help!

Regards!

**Comment by krigeta** [comment]
Hello, if you want to know what are the steps then:
1) open Steamless.exe then select the exe file of a steam game you want to unpack (Remove the DRM layer).
2) then tick the keep binding question and select the automatic option in the dropdown.
3) then click "unpack", it works then you will be able to play the game but if it is not then you cant post about it here or you cant unpack the exe because of security reasons.

Thank you

**Comment by atom0s** [comment]
If you are unsure of how to use this tool, then I would assume you are not using it for its intended purpose.
