### ISSUE TITLE
Unable to unpack 1953 - KGB Unleashed

### ISSUE THREAD

**Issue by Ekey** [atom0s/Steamless#57]
Hi there. Can you check it please? 3.0.0.11 dumping only SteamDRMP.dll

![Screenshot_1](https://user-images.githubusercontent.com/1664144/134068721-55c82865-37e2-4ae6-84c0-3c787ccdd86a.png)

Executable
[Phobos_1953.zip](https://github.com/atom0s/Steamless/files/7198489/Phobos_1953.zip)

Thanks  advance

**Comment by atom0s** [comment]
~~This file is double packed, which is why Steamlesss is failing. You need to remove the other protection layer first since it was applied after Steam's DRM system was used. Afterward, Steamless should work fine.~~

**Comment by atom0s** [comment]
Sorry about the above, appears my private tool had a bug and was misdetecting something with this file. 
It is not double packed.

Reopening til I have more time to take a better look.

**Comment by atom0s** [comment]
This is now fixed in the current repo. Was due to invalid size of data being used for the decryption step of the .text section. This should now work properly for the given file as well as work better/proper for all 2.1 (x86) protected files going forward. 

A release will be made soon with this update in it as well.
