### ISSUE TITLE
Unable to unpack MonsterHunterRiseDemo

### ISSUE THREAD

**Issue by kennedyoliveira** [atom0s/Steamless#65]
Monster Hunter Rise Demo fails to unpack.

When I try to upload the executable it fails with "is not supported on the list", even though I zipped it.

Here is the link to the exe. https://drive.google.com/file/d/16EWN2N5M4yVy75_DCUpg7X9JUcIn0cnX/view?usp=sharing

**Comment by atom0s** [comment]
This was failing to unpack because the file is first protected with the latest version of VMProtect. When protected with virtualization and encryption, the entire `.text` section is replaced and moved to a new section injected into the file. The failure was happening due to Steamless not knowing how to handle the empty `.text` section.

This is fixed for the v3.1 x64 variant plugin now. Will add this fix to others as files appear with the same problem and it starts being an issue.
