### ISSUE TITLE
Calculated checksum is invalid

### ISSUE THREAD

**Issue by GitHubUser99** [atom0s/Steamless#74]
On "Recalculate file checksum" selected -> unpacked exe checksum is invalid. On every file unpacked, tested. For example, CFF Explorer option Update checksum on such Steamless unpacked file will generate correct checksum, different from what Steamless generates.

Small suggestion , when "Recalculate file checksum" option is not selected Steamless will overwrite checksum with zeroes (not existent)...this is correct way but if possible, it would be better to enable  "third" option (grayed checkbox maybe?), that leaves checksum bytes untouched/unmodified, as it was in 3.0.0.12 version. 

Also, why there is still garbage zeroes 00 appended at file end when unpacking with "Keep bind section" and "Don't Realign Sections"? File size should be the same as in original but all Steamless versions adds padding 00 bytes so unpacked file size is unnecessary altered.

**Comment by atom0s** [comment]
Steamless' original goal was simply to unpack files enough to allow for static analysis. Making things runnable wasn't my priority before when I wrote the first versions of Steamless. That said, over time the unpackers have evolved into ensuring things are either as close to runnable as possible or will run as-is after being unpacked. However, due to the way some things were originally designed, there are some bugs still in the unpackers.

Things like extra bytes/data after decryption and such are a known issue and will be dealt with later on. The checksum may be incorrect due to those bugs, but the algorithm being used is directly from Microsoft and how they explain it is calculated.

**Comment by atom0s** [comment]
> On "Recalculate file checksum" selected -> unpacked exe checksum is invalid. On every file unpacked, tested. For example, CFF Explorer option Update checksum on such Steamless unpacked file will generate correct checksum, different from what Steamless generates.

Had some time tonight to check this out. I can't recreate this issue. Using CEF's `Recalculate Checksum` feature, I am seeing the same checksum being generated as Steamless. If I force the checksum to 0, then have CEF recalculate it as well, it also still generates the same as Steamless. _(Which is correct as the Checksum bytes are ignored when it is calculated.)_

If there is a specific file you are seeing this issue with, or multiple files, can you upload them somewhere and I can take a look.

> Small suggestion , when "Recalculate file checksum" option is not selected Steamless will overwrite checksum with zeroes (not existent)...this is correct way but if possible, it would be better to enable "third" option (grayed checkbox maybe?), that leaves checksum bytes untouched/unmodified, as it was in 3.0.0.12 version.

I'll keep this in mind for the next major update(s) to add this back as some games may have checks for the checksum.

**Comment by GitHubUser99** [comment]
[ChecksumExample.zip](https://github.com/atom0s/Steamless/files/8557561/ChecksumExample.zip)
In attachment there are examples from pinball game that is available for download as demo from Steam for everybody. File names are self-explanatory (original/untouched exe in attachment has invalid checksum but this is irrelevant). But it is not tied to specific file, tried with multiple different exes and Steamless unpacked exe always have different (wrong) checksum than what other programs generates on that same unpacked file. Maybe your calculation is somehow tied to something specific to different version of Windows (I tested on Win 10 21H2 btw), regional settings or something (just guessing, I could be completely wrong about this).

**Comment by atom0s** [comment]
Are you certain you are using the latest version of Steamless? The files in that zip look to be incorrectly handled in various parts such as the section realignments and such. Which was something that was fixed in a more recent update of Steamless. Using the latest release I published, the resulting unpacked file does not match yours, even if I match the same options you used.

As for the calculation handling, it is not tied to any system information or similar. It's strictly only done using the file data itself.

**Comment by GitHubUser99** [comment]
Yes, I downloaded 3.1.0.0 again just to be sure. I used "Keep bind section", "unselected Zero DOS stub data", leave "Don't realign sections" and checked "Recalculate file checksum".  In CFF Explorer i forgot to uncheck "Rebuild PE Header" so steamless unpacked exe with checksum overwritten from CFF Explorer have different realignments. I'm uploading another one here
[ChecksumExample2.zip](https://github.com/atom0s/Steamless/files/8557731/ChecksumExample2.zip)
.

**Comment by GitHubUser99** [comment]
Just to make sure, I tried Steamless 3.1.0.0 on another computer with Windows 11 - same thing. Unpacked files are good (same thing on every SteamStub exe), everything is ok but checksum is invalid. Like in attachment from previous message - I can correct checksum with CFF Explorer. Files will be binary identical except checksum bytes (selected options in Steamless are not really important - no matter what other option I select besides "Recalculate file checksum" it will always generate unpacked files with wrong checksum for me)

**Comment by GitHubUser99** [comment]
I can confirm problem with checksum is fixed in latest 3.1.0.2 version. Thanks!
P.S. Still waiting for "leave checksum as in original" option (or better, three-check option on recalculate checksum..) since latest version (if not set to recalculated) writes checksum as not-defined (zeroes). This is correct behavior but there are times when you want this bytes to be as in original.
