### ISSUE TITLE
64 bits test files for new SteamStub v3.1.2 variant

### ISSUE THREAD

**Issue by wscmdyzk** [atom0s/Steamless#8]
Hello atom0s:

Thanks for your amazing work!

I think you need 64 bits test files for new SteamStub v3.1.2 variant.
Here are two games which use that.

< Links Removed >

Regards.

**Comment by atom0s** [comment]
Thanks for the files/links. I've removed the links since they contained more than just the exe files. To avoid any legal issues / troubles, I only ask for the exe so I have no way to run the game illegally etc. 

I don't have the time to look into these files at the moment but I have downloaded them and archived them for later.
