### ISSUE TITLE
Found 2 older exe's with invalid/unknown variant header size: 884

### ISSUE THREAD

**Issue by kasha695** [atom0s/Steamless#86]
I'm currently working through my 200 odd Steam games to make sure I have working offline backups.

I've come across 2 exe's so far that both report the same error:
`[Steamless.Unpacker.Variant20.x86] Invalid/unknown variant header size: 884`

I'll probably find some more older title exe's as I work further through my list.

I've attached both files for now.

[Exe1.tar.gz](https://github.com/atom0s/Steamless/files/9644754/Exe1.tar.gz)
[Exe2.tar.gz](https://github.com/atom0s/Steamless/files/9644755/Exe2.tar.gz)

**Comment by atom0s** [comment]
Thanks for the additional samples, this version of the 2.0 variant is now supported in latest: https://github.com/atom0s/Steamless/commit/640e57e1483655cbe8431bdd6699615159a1daaa

_I'm going to hold off on pushing a full release for now though since I just did a few releases this past week already. But the changes are live in the repo now if you want to self-compile._
