### ISSUE TITLE
This runs games without steam but it doesn't (?) confused about the legal stuff warnings.

### ISSUE THREAD

**Issue by Shituation** [atom0s/Steamless#88]
The readme confuses me. 
Making it short: does steamless make possible to run games without steam or not? what is the point of this software?
 I don't like steam because of the data sucking practices of these guys. Does steamless make me able to run say, [legit] flight simulator without having steam open?

**Comment by atom0s** [comment]
Not sure what is confusing, as the README clearly states what Steamless will not do.

<hr>

Steamless **WILL NEVER** do any of the following:

  - Steamless will never remove the Steamworks API integration. (via steam_api.dll/steam_api64.dll)
  - Steamless will never include or distribute any emulator for the Steamworks API integration.
  - Steamless will never handle Valve's CEG (Custom Executable Generation) DRM that is used on some older games.
  - Steamless will never promote, encourage, or assist with piracy.
  - Steamless will never assist with bypassing anti-cheats or other protections in place by games.
  - Do not ask for help with running games without Steam. Your requests will be ignored/blocked.

That is not the scope or goal of this project.

<hr>

The point of this software is to remove the SteamStub DRM layer of protection. This is useful for debugging, reverse engineering and modding games that are otherwise difficult to debug or work on due to SteamStub encrypting the `.text` section of the file most of the time.

The point of this software **IS NOT** piracy. The point is not to fully remove Steam altogether either, such as if the game makes use of the SteamWorks API (steam_api.dll / steam_api64.dll) or has any additional custom checks to ensure Steam is running.
